version: "3.9"

networks:
  app:
    driver: bridge
  db:
    driver: bridge

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: booking
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - db

  nestjs:
    container_name: backend
    build: ./backend
    ports:
      - 3002:3000
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - app
      - db

  react:
    build: ./frontend
    env_file:
      - ./.env
    volumes:
      - ./frontend:/app
    ports:
      - 3003:3000
    networks:
      - app