version: "3.9"

networks:
  app:
    driver: bridge

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: booking
    ports:
      - 27017:27017
    networks:
      - app

  nestjs:
    container_name: backend_nestjs
    build: ./backend
    ports:
      - 3002:3000
    restart: always
    depends_on:
      - mongo
    networks:
      - app

  react:
    container_name: frontend_react
    build: ./frontend
    ports:
      - 3003:3000
    networks:
      - app